name: Build and Scan
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code and install Node.js
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies  
        run: npm ci
      - name: Run application
        run: nohup npm run start &
      - name: hawk scan run
        uses: stackhawk/hawkscan-action@v2.0.3
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        
    

